/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 Source Host           : localhost:1521
 Source Schema         : HLWJ

 Target Server Type    : Oracle
 Target Server Version : 110200 (Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options)
 File Encoding         : 65001

 Date: 11/04/2024 19:26:10
*/


-- ----------------------------
-- Table structure for CONVERT_DATA
-- ----------------------------
DROP TABLE "HLWJ"."CONVERT_DATA";
CREATE TABLE "HLWJ"."CONVERT_DATA" (
  "APPLY_FROM" VARCHAR2(255 BYTE),
  "WSSP_DATA_TYPE" VARCHAR2(255 BYTE),
  "UNID" VARCHAR2(50 BYTE) NOT NULL,
  "XSD" VARCHAR2(255 BYTE),
  "RESOURCEINFO_TYPE" VARCHAR2(5 BYTE),
  "OPERATION_LOGO" VARCHAR2(2 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "HLWJ"."CONVERT_DATA"."RESOURCEINFO_TYPE" IS '地市级别属性  999代表市里   99代表省厅';
COMMENT ON COLUMN "HLWJ"."CONVERT_DATA"."OPERATION_LOGO" IS '省厅操作标识 1操作成功  2重复  3其他错误';

-- ----------------------------
-- Table structure for DOCUMENT
-- ----------------------------
DROP TABLE "HLWJ"."DOCUMENT";
CREATE TABLE "HLWJ"."DOCUMENT" (
  "DOCUMENT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "DOC_UNID" VARCHAR2(50 BYTE),
  "SWB_TYPE" VARCHAR2(255 BYTE),
  "SRC_TYPE" VARCHAR2(255 BYTE),
  "DOC_TYPE" VARCHAR2(255 BYTE),
  "DOC_NAME" VARCHAR2(255 BYTE),
  "DOC_NO" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINISH_APASINFO
-- ----------------------------
DROP TABLE "HLWJ"."FINISH_APASINFO";
CREATE TABLE "HLWJ"."FINISH_APASINFO" (
  "FINISH_APASINFO_ID" VARCHAR2(50 BYTE) NOT NULL,
  "PROJECT_CODE" VARCHAR2(255 BYTE),
  "APPLY_TYPE" VARCHAR2(255 BYTE),
  "FROM_CODE" VARCHAR2(255 BYTE),
  "SWB_MATTER_ID" VARCHAR2(255 BYTE),
  "SWB_MATTER_NAME" VARCHAR2(255 BYTE),
  "SRC_MATTER_ID" VARCHAR2(255 BYTE),
  "AREA_CODE" VARCHAR2(255 BYTE),
  "PROJECT_NAME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_NAME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_CODE" VARCHAR2(255 BYTE),
  "SWB_SN" VARCHAR2(255 BYTE),
  "SRC_SN" VARCHAR2(255 BYTE),
  "VERSION" NUMBER,
  "PROCESSED_USER" VARCHAR2(255 BYTE),
  "PROCESSED_TIME" VARCHAR2(255 BYTE),
  "RESULT" VARCHAR2(255 BYTE),
  "DELIVERY_RESULT" VARCHAR2(255 BYTE),
  "PROCESSED_OPINION" VARCHAR2(255 BYTE),
  "OPEN_WAY" VARCHAR2(255 BYTE),
  "IS_OPEN" VARCHAR2(255 BYTE),
  "IS_EXIST_LICENCE" VARCHAR2(255 BYTE),
  "DEPT_CODE" VARCHAR2(255 BYTE),
  "DEPT_NAME" VARCHAR2(255 BYTE),
  "RESULT_TYPE" NUMBER,
  "RESULT_DESC" VARCHAR2(255 BYTE),
  "ABN_CAUSE" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINISH_ATTR
-- ----------------------------
DROP TABLE "HLWJ"."FINISH_ATTR";
CREATE TABLE "HLWJ"."FINISH_ATTR" (
  "ATTR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ATTRUNID" VARCHAR2(255 BYTE),
  "ATTRMODE" VARCHAR2(255 BYTE),
  "SWBCODE" VARCHAR2(255 BYTE),
  "SRCCODE" VARCHAR2(255 BYTE),
  "ATTRNAME" VARCHAR2(255 BYTE),
  "SORT" NUMBER,
  "FILENAME" VARCHAR2(255 BYTE),
  "DATASHARE" VARCHAR2(255 BYTE),
  "LICENSEIDENTIFIER" VARCHAR2(255 BYTE),
  "CERTIFICATETYPECODE" VARCHAR2(255 BYTE),
  "CERTIFICATEHOLDERCODE" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINISH_LICENSE
-- ----------------------------
DROP TABLE "HLWJ"."FINISH_LICENSE";
CREATE TABLE "HLWJ"."FINISH_LICENSE" (
  "FINISH_LICENSE_ID" VARCHAR2(50 BYTE) NOT NULL,
  "DOC_TYPE" VARCHAR2(255 BYTE),
  "SEQ_NO" VARCHAR2(255 BYTE),
  "LICENSE_NAME" VARCHAR2(255 BYTE),
  "START_DATE" VARCHAR2(255 BYTE),
  "VALIDATE_DATE" VARCHAR2(255 BYTE),
  "CERT_UNIT" VARCHAR2(255 BYTE),
  "CERT_UNIT_CODE" VARCHAR2(255 BYTE),
  "CERT_CONTENT" VARCHAR2(255 BYTE),
  "CERTIFIED_TIME" VARCHAR2(255 BYTE),
  "HOLDER" VARCHAR2(255 BYTE),
  "CERTIFICATE_HOLDER_CODE" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINISH_RESULT_ATTR
-- ----------------------------
DROP TABLE "HLWJ"."FINISH_RESULT_ATTR";
CREATE TABLE "HLWJ"."FINISH_RESULT_ATTR" (
  "FINISH_RESULT_ATTR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UNID" VARCHAR2(255 BYTE),
  "ATTR_CATEGORY" VARCHAR2(255 BYTE),
  "ATTR_NAME" VARCHAR2(255 BYTE),
  "ATTR_NUMBER" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FINISH_SMS
-- ----------------------------
DROP TABLE "HLWJ"."FINISH_SMS";
CREATE TABLE "HLWJ"."FINISH_SMS" (
  "FINISH_SMS_ID" VARCHAR2(50 BYTE) NOT NULL,
  "RECEIVER" VARCHAR2(255 BYTE),
  "ADDRESS" VARCHAR2(255 BYTE),
  "CONTENT" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FORM_INFO
-- ----------------------------
DROP TABLE "HLWJ"."FORM_INFO";
CREATE TABLE "HLWJ"."FORM_INFO" (
  "FORM_INFO_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UNID" VARCHAR2(50 BYTE),
  "FORM_NAME" VARCHAR2(255 BYTE),
  "FORM_ALIAS" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for FORM_INFO_ITEM
-- ----------------------------
DROP TABLE "HLWJ"."FORM_INFO_ITEM";
CREATE TABLE "HLWJ"."FORM_INFO_ITEM" (
  "ITEM_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ALIAS" VARCHAR2(255 BYTE),
  "FIELD" VARCHAR2(255 BYTE),
  "ITEM_VALUE" VARCHAR2(500 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for NEXT_APAS_INFO
-- ----------------------------
DROP TABLE "HLWJ"."NEXT_APAS_INFO";
CREATE TABLE "HLWJ"."NEXT_APAS_INFO" (
  "NEXT_APAS_INFO_ID" VARCHAR2(50 BYTE) NOT NULL,
  "PROJECT_CODE" VARCHAR2(255 BYTE),
  "APPLY_TYPE" VARCHAR2(255 BYTE),
  "FROM_CODE" VARCHAR2(255 BYTE),
  "SWB_MATTER_ID" VARCHAR2(255 BYTE),
  "SWB_MATTER_NAME" VARCHAR2(255 BYTE),
  "SRC_MATTER_ID" VARCHAR2(255 BYTE),
  "AREA_CODE" VARCHAR2(255 BYTE),
  "PROJECT_NAME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_NAME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_CODE" VARCHAR2(255 BYTE),
  "SWB_SN" VARCHAR2(255 BYTE),
  "SRC_SN" VARCHAR2(255 BYTE),
  "SEQ_NO" VARCHAR2(255 BYTE),
  "VERSION" NUMBER,
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for NEXT_ATTR
-- ----------------------------
DROP TABLE "HLWJ"."NEXT_ATTR";
CREATE TABLE "HLWJ"."NEXT_ATTR" (
  "NEXT_ATTR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ATTR_UNID" VARCHAR2(255 BYTE),
  "ATTR_SORT" VARCHAR2(255 BYTE),
  "ATTR_NAME" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for NEXT_NODE
-- ----------------------------
DROP TABLE "HLWJ"."NEXT_NODE";
CREATE TABLE "HLWJ"."NEXT_NODE" (
  "NEXT_NODE_ID" VARCHAR2(50 BYTE) NOT NULL,
  "IS_SPECIAL" VARCHAR2(255 BYTE),
  "NODE_GUID" VARCHAR2(255 BYTE),
  "SWB_CODE" VARCHAR2(255 BYTE),
  "SWB_NAME" VARCHAR2(255 BYTE),
  "DZJC_CODE" VARCHAR2(255 BYTE),
  "DZJC_NAME" VARCHAR2(255 BYTE),
  "SRC_NAME" VARCHAR2(255 BYTE),
  "NEXT_NAME" VARCHAR2(255 BYTE),
  "NEXT_USER" VARCHAR2(255 BYTE),
  "PROCESSED_USER" VARCHAR2(255 BYTE),
  "PROCESSED_USER_POSITION" VARCHAR2(255 BYTE),
  "PROCESSED_USER_PT_CODE" VARCHAR2(255 BYTE),
  "PROCESSED_USER_CODE" VARCHAR2(255 BYTE),
  "START_TIME" VARCHAR2(255 BYTE),
  "PROCESSED_TIME" VARCHAR2(255 BYTE),
  "TYPE" VARCHAR2(255 BYTE),
  "PROCESSED_OPINION" VARCHAR2(255 BYTE),
  "PROMISE_END_TIME" VARCHAR2(255 BYTE),
  "IS_ACPT" VARCHAR2(255 BYTE),
  "NO_ACPT_CAUSE" VARCHAR2(255 BYTE),
  "OTHER_INFO" VARCHAR2(255 BYTE),
  "REMARK" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for ROUTER
-- ----------------------------
DROP TABLE "HLWJ"."ROUTER";
CREATE TABLE "HLWJ"."ROUTER" (
  "ROUTER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "FROM_AREA_CODE" VARCHAR2(255 BYTE),
  "FROM_AREA_NAME" VARCHAR2(255 BYTE),
  "TO_AREA_CODE" VARCHAR2(255 BYTE),
  "TO_AREA_NAME" VARCHAR2(255 BYTE),
  "TARGET_SYSTEM" VARCHAR2(255 BYTE),
  "SEND_TIME" VARCHAR2(255 BYTE),
  "PREV_LINK_UNID" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SPECIAL_END
-- ----------------------------
DROP TABLE "HLWJ"."SPECIAL_END";
CREATE TABLE "HLWJ"."SPECIAL_END" (
  "SPECIAL_END_ID" VARCHAR2(50 BYTE) NOT NULL,
  "OPER_USER" VARCHAR2(255 BYTE),
  "RESULT" VARCHAR2(255 BYTE),
  "RESULT_TIME" VARCHAR2(255 BYTE),
  "END_TIME" VARCHAR2(255 BYTE),
  "SPECIAL_END_CHARGE_AMOUNT" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SPECIAL_START
-- ----------------------------
DROP TABLE "HLWJ"."SPECIAL_START";
CREATE TABLE "HLWJ"."SPECIAL_START" (
  "SPECIAL_START_ID" VARCHAR2(50 BYTE) NOT NULL,
  "CLASS_CODE" VARCHAR2(255 BYTE),
  "CLASS_NAME" VARCHAR2(255 BYTE),
  "START_TIME" VARCHAR2(255 BYTE),
  "APPROVE_USER" VARCHAR2(255 BYTE),
  "APPROVE_USER_TEL" VARCHAR2(255 BYTE),
  "APPROVE_USER_MOBI" VARCHAR2(255 BYTE),
  "BASIS" VARCHAR2(255 BYTE),
  "CONTENT" VARCHAR2(4000 BYTE),
  "LIMIT_VAL" VARCHAR2(255 BYTE),
  "LIMIT_UNIT" VARCHAR2(255 BYTE),
  "PRE_END_TIME" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SUPP_MAT
-- ----------------------------
DROP TABLE "HLWJ"."SUPP_MAT";
CREATE TABLE "HLWJ"."SUPP_MAT" (
  "SUPP_MAT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SM_TYPE" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SUPP_MAT_START
-- ----------------------------
DROP TABLE "HLWJ"."SUPP_MAT_START";
CREATE TABLE "HLWJ"."SUPP_MAT_START" (
  "SUPP_MAT_START_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SM_SEND_USER" VARCHAR2(255 BYTE),
  "SM_CAUSE" VARCHAR2(255 BYTE),
  "SM_SEND_TIME" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for SUPP_MAT_START_ATTR
-- ----------------------------
DROP TABLE "HLWJ"."SUPP_MAT_START_ATTR";
CREATE TABLE "HLWJ"."SUPP_MAT_START_ATTR" (
  "SUPP_MAT_START_ATTR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SUPP_MAT_START_ATTR_SWB_CODE" VARCHAR2(255 BYTE),
  "SUPP_MAT_START_ATTR_SRC_CODE" VARCHAR2(255 BYTE),
  "SUPP_MAT_START_ATTR_NAME" VARCHAR2(255 BYTE),
  "SUPP_MAT_START_ATTR_SEQ_NO" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_APASINFO
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_APASINFO";
CREATE TABLE "HLWJ"."WSSP_APASINFO" (
  "APASINFO_ID" VARCHAR2(50 BYTE) NOT NULL,
  "PROJECT_CODE" VARCHAR2(255 BYTE),
  "FROM_CODE" VARCHAR2(255 BYTE),
  "SWB_SERVICE_ID" VARCHAR2(255 BYTE),
  "SWB_MATTER_ID" VARCHAR2(255 BYTE),
  "SWB_MATTER_NAME" VARCHAR2(255 BYTE),
  "SRC_MATTER_ID" VARCHAR2(255 BYTE),
  "AREA_CODE" VARCHAR2(255 BYTE),
  "PROJECT_NAME" VARCHAR2(255 BYTE),
  "PROMISE_DAY" NUMBER,
  "PROMISE_DAY_UNIT" VARCHAR2(255 BYTE),
  "SWB_SN" VARCHAR2(255 BYTE),
  "SRC_SN" VARCHAR2(255 BYTE),
  "VERSION" NUMBER,
  "PWD" VARCHAR2(255 BYTE),
  "DECLARE_TIME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_NAME" VARCHAR2(255 BYTE),
  "RECEIVE_DEPT_CODE" VARCHAR2(255 BYTE),
  "ACCEPT_ADDRESS" VARCHAR2(255 BYTE),
  "SUB_WAY" NUMBER,
  "QUEUING_NO" VARCHAR2(255 BYTE),
  "CENTRAL_APPROVAL_ITEMID" VARCHAR2(255 BYTE),
  "REL_ITEM_FLAG" VARCHAR2(255 BYTE),
  "REL_DEPT_CODE" VARCHAR2(255 BYTE),
  "REL_CENTRAL_ITEM_CODE" VARCHAR2(255 BYTE),
  "CLASS_UNID" VARCHAR2(255 BYTE),
  "CLASS_NAME" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_ATTR
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_ATTR";
CREATE TABLE "HLWJ"."WSSP_ATTR" (
  "ATTR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "ATTR_UNID" VARCHAR2(50 BYTE),
  "ATTR_MODE" VARCHAR2(255 BYTE),
  "SWB_CODE" VARCHAR2(255 BYTE),
  "SRC_CODE" VARCHAR2(255 BYTE),
  "NAME" VARCHAR2(255 BYTE),
  "SORT" VARCHAR2(255 BYTE),
  "FILE_NAME" VARCHAR2(255 BYTE),
  "DATASHARE" VARCHAR2(255 BYTE),
  "LICENSE_IDENTIFIER" VARCHAR2(255 BYTE),
  "CERTIFICATE_TYPE_CODE" VARCHAR2(255 BYTE),
  "CERTIFICATE_HOLDER_CODE" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_CLOUD_FORM
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_CLOUD_FORM";
CREATE TABLE "HLWJ"."WSSP_CLOUD_FORM" (
  "CLOUD_FORM_ID" VARCHAR2(50 BYTE) NOT NULL,
  "INTRANET_URL" VARCHAR2(255 BYTE),
  "OUTERNET_URL" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_EXPRESS
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_EXPRESS";
CREATE TABLE "HLWJ"."WSSP_EXPRESS" (
  "EXPRESS_ID" VARCHAR2(50 BYTE) NOT NULL,
  "RECIPIENTS" VARCHAR2(255 BYTE),
  "R_CITY" VARCHAR2(255 BYTE),
  "R_ADDRESS" VARCHAR2(255 BYTE),
  "R_AREA_CODE" VARCHAR2(255 BYTE),
  "R_MOBILE" VARCHAR2(255 BYTE),
  "R_CONTACT_NUMBER" VARCHAR2(255 BYTE),
  "R_PAY_TYPE" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_EXTEND
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_EXTEND";
CREATE TABLE "HLWJ"."WSSP_EXTEND" (
  "EXTEND_ID" VARCHAR2(50 BYTE) NOT NULL,
  "IS_AGENT_SERVICE" VARCHAR2(255 BYTE),
  "AGENT_SERVICE_CHARGE" VARCHAR2(255 BYTE),
  "BACKFLOW" VARCHAR2(255 BYTE),
  "GZCNSP_FLAG" VARCHAR2(255 BYTE),
  "GZCNSP_FILE_UNID" VARCHAR2(255 BYTE),
  "GZCNSP_FILE_NAME" VARCHAR2(255 BYTE),
  "AGENT_SOURCE_AREA" VARCHAR2(255 BYTE),
  "CERTIFIED_IS_WRITE_OFF" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_OPERATOR
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_OPERATOR";
CREATE TABLE "HLWJ"."WSSP_OPERATOR" (
  "OPERATOR_ID" VARCHAR2(50 BYTE) NOT NULL,
  "OPERATOR_APPLY_NAME" VARCHAR2(255 BYTE),
  "OPERATOR_SEX" VARCHAR2(255 BYTE),
  "OPERATOR_BIRTHDAY" VARCHAR2(255 BYTE),
  "OPERATOR_CERTIFICATE_TYPE" VARCHAR2(255 BYTE),
  "OPERATOR_CERTIFICATE_NAME" VARCHAR2(255 BYTE),
  "OPERATOR_CERTIFICATE_NUMBER" VARCHAR2(255 BYTE),
  "OPERATOR_ADDRESS" VARCHAR2(255 BYTE),
  "OPERATOR_POSTCODE" VARCHAR2(255 BYTE),
  "OPERATOR_MOBILE_PHONE" VARCHAR2(255 BYTE),
  "OPERATOR_MAIL" VARCHAR2(255 BYTE),
  "OPERATOR_TEL" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_PERSON
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_PERSON";
CREATE TABLE "HLWJ"."WSSP_PERSON" (
  "WSSP_PERSON_ID" VARCHAR2(50 BYTE) NOT NULL,
  "APPLYNAME" VARCHAR2(255 BYTE),
  "SEX" VARCHAR2(255 BYTE),
  "BIRTHDAY" VARCHAR2(255 BYTE),
  "CERTIFICATETYPE" VARCHAR2(255 BYTE),
  "CERTIFICATENAME" VARCHAR2(255 BYTE),
  "CERTIFICATENUMBER" VARCHAR2(255 BYTE),
  "ADDRESS" VARCHAR2(255 BYTE),
  "POSTCODE" VARCHAR2(255 BYTE),
  "MOBILEPHONE" VARCHAR2(255 BYTE),
  "MAIL" VARCHAR2(255 BYTE),
  "TEL" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_PROPOSER
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_PROPOSER";
CREATE TABLE "HLWJ"."WSSP_PROPOSER" (
  "PROPOSER_ID" VARCHAR2(50 BYTE) NOT NULL,
  "APPLY_TYPE" VARCHAR2(255 BYTE),
  "APPLY_OBJ_AREA_CODE" VARCHAR2(255 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_SMS
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_SMS";
CREATE TABLE "HLWJ"."WSSP_SMS" (
  "SMS_ID" VARCHAR2(50 BYTE) NOT NULL,
  "SMS_RECEIVER" VARCHAR2(255 BYTE),
  "SMS_ADDRESS" VARCHAR2(255 BYTE),
  "SMS_CONTENT" VARCHAR2(500 BYTE),
  "BUSISYSINFO_UUID" VARCHAR2(50 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for WSSP_UNIT
-- ----------------------------
DROP TABLE "HLWJ"."WSSP_UNIT";
CREATE TABLE "HLWJ"."WSSP_UNIT" (
  "UNIT_ID" VARCHAR2(50 BYTE) NOT NULL,
  "UNIT_NAME" VARCHAR2(255 BYTE),
  "UNIT_CODE" VARCHAR2(255 BYTE),
  "UNIT_TYPE" VARCHAR2(255 BYTE),
  "UNIT_IDCARD_TYPE" VARCHAR2(255 BYTE),
  "LEAL_PERSON" VARCHAR2(255 BYTE),
  "LEGAL_IDCARD_TYPE" VARCHAR2(255 BYTE),
  "LEGAL_IDCARD" VARCHAR2(255 BYTE),
  "UNIT_ADDRESS" VARCHAR2(255 BYTE),
  "UNIT_TEL" VARCHAR2(255 BYTE),
  "UNIT_POSTCODE" VARCHAR2(255 BYTE),
  "COMPANY_PHONE" VARCHAR2(255 BYTE),
  "DATA_ID" VARCHAR2(255 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- View structure for FINISH_DATA_VIEW
-- ----------------------------
CREATE OR REPLACE VIEW "HLWJ"."FINISH_DATA_VIEW" AS SELECT
	a.UNID,
  a.APPLY_FROM,
  a.WSSP_DATA_TYPE,
  a.XSD,
	k.FROM_AREA_CODE,
	k.FROM_AREA_NAME,
	k.TO_AREA_CODE,
	k.TO_AREA_NAME,
	k.TARGET_SYSTEM,
	k.SEND_TIME,
	k.PREV_LINK_UNID,
	b.PROJECT_CODE,
	b.APPLY_TYPE,
	b.FROM_CODE,
	b.SWB_MATTER_ID,
	b.SWB_MATTER_NAME,
	b.SRC_MATTER_ID,
	b.AREA_CODE,
	b.PROJECT_NAME,
	b.RECEIVE_DEPT_NAME,
	b.RECEIVE_DEPT_CODE,
	b.SWB_SN,
	b.SRC_SN,
	b.VERSION,
	b.PROCESSED_USER,
	b.PROCESSED_TIME,
	b.RESULT,
	b.DELIVERY_RESULT,
	b.PROCESSED_OPINION,
	b.OPEN_WAY,
	b.IS_OPEN,
	b.IS_EXIST_LICENCE,
	b.DEPT_CODE,
	b.DEPT_NAME,
	b.RESULT_TYPE,
	b.RESULT_DESC,
	b.ABN_CAUSE,
	c.RECEIVER,
	c.ADDRESS,
	c.CONTENT,
	a.RESOURCEINFO_TYPE,
	a.OPERATION_LOGO,
	 (SELECT COUNT(0) FROM HLWJ.DOCUMENT d WHERE d.DATA_ID = a.UNID) AS DOCUMENT_DATA,
	 (SELECT COUNT(0) FROM HLWJ.FINISH_ATTR e WHERE e.DATA_ID = a.UNID) AS FINISH_ATTR_DATA,
	 (SELECT COUNT(0) FROM HLWJ.FINISH_LICENSE f WHERE f.BUSISYSINFO_UUID = a.UNID) AS FINISH_LICENSE_DATA,
	 (SELECT COUNT(0) FROM HLWJ.FINISH_RESULT_ATTR g WHERE g.BUSISYSINFO_UUID = a.UNID) AS RESULT_ATTR_DATA,
	 (SELECT COUNT(0) FROM HLWJ.FORM_INFO h WHERE h.BUSISYSINFO_UUID = a.UNID) AS FORM_INFO_DATA,
   (SELECT COUNT(0) FROM HLWJ.FORM_INFO_ITEM i,HLWJ.FORM_INFO j WHERE j.BUSISYSINFO_UUID = a.UNID AND i.DATA_ID = j.FORM_INFO_ID) AS INFO_ITEM_DATA
FROM
	HLWJ.CONVERT_DATA a
	LEFT JOIN HLWJ.FINISH_APASINFO b ON a.UNID = b.BUSISYSINFO_UUID
	LEFT JOIN HLWJ.FINISH_SMS c ON c.BUSISYSINFO_UUID = a.UNID 
	LEFT JOIN HLWJ.ROUTER k ON k.DATA_ID = a.UNID 
WHERE
	a.WSSP_DATA_TYPE = '230';

-- ----------------------------
-- View structure for NEXT_DATA_VIEW
-- ----------------------------
CREATE OR REPLACE VIEW "HLWJ"."NEXT_DATA_VIEW" AS SELECT
	a.UNID,
  a.APPLY_FROM,
  a.WSSP_DATA_TYPE,
  a.XSD,
	k.FROM_AREA_CODE,
	k.FROM_AREA_NAME,
	k.TO_AREA_CODE,
	k.TO_AREA_NAME,
	k.TARGET_SYSTEM,
	k.SEND_TIME,
	k.PREV_LINK_UNID,
	b.PROJECT_CODE,
	b.APPLY_TYPE,
	b.FROM_CODE,
	b.SWB_MATTER_ID,
	b.SWB_MATTER_NAME,
	b.SRC_MATTER_ID,
	b.AREA_CODE,
	b.PROJECT_NAME,
	b.RECEIVE_DEPT_NAME,
	b.RECEIVE_DEPT_CODE,
	b.SWB_SN,
	b.SRC_SN,
	b.SEQ_NO,
	b.VERSION,
	c.IS_SPECIAL,
	c.NODE_GUID,
	c.SWB_CODE,
	c.SWB_NAME,
	c.DZJC_CODE,
	c.DZJC_NAME,
	c.SRC_NAME,
	c.NEXT_NAME,
	c.NEXT_USER,
	c.PROCESSED_USER,
	c.PROCESSED_USER_POSITION,
	c.PROCESSED_USER_PT_CODE,
	c.PROCESSED_USER_CODE,
	c.START_TIME,
	c.PROCESSED_TIME,
	c.TYPE,
	c.PROCESSED_OPINION,
	c.PROMISE_END_TIME,
	c.IS_ACPT,
	c.NO_ACPT_CAUSE,
	c.OTHER_INFO,
	c.REMARK,
	a.RESOURCEINFO_TYPE,
	a.OPERATION_LOGO,
	(SELECT COUNT(0) FROM HLWJ.NEXT_ATTR e WHERE e.DATA_ID = a.UNID) AS NEXT_ATTR,
	(SELECT COUNT(0) FROM HLWJ.DOCUMENT f WHERE f.DATA_ID = a.UNID) AS NEXT_DOCUMENT
FROM
	 HLWJ.CONVERT_DATA a
	LEFT JOIN HLWJ.NEXT_APAS_INFO b ON a.UNID = b.BUSISYSINFO_UUID
	LEFT JOIN HLWJ.NEXT_NODE c ON c.BUSISYSINFO_UUID = b.BUSISYSINFO_UUID
	LEFT JOIN HLWJ.ROUTER k ON k.DATA_ID = b.BUSISYSINFO_UUID
	WHERE
	a.WSSP_DATA_TYPE='220';

-- ----------------------------
-- View structure for WSSP_DATA_VIEW
-- ----------------------------
CREATE OR REPLACE VIEW "HLWJ"."WSSP_DATA_VIEW" AS SELECT
		a.UNID,
    a.APPLY_FROM,
    a.WSSP_DATA_TYPE,
    a.XSD,
		l.FROM_AREA_CODE,
		l.FROM_AREA_NAME,
		l.TO_AREA_CODE,
		l.TO_AREA_NAME,
		l.TARGET_SYSTEM,
		l.SEND_TIME,
		l.PREV_LINK_UNID,
    b.APASINFO_ID,
    b.PROJECT_CODE,
    b.FROM_CODE,
    b.SWB_SERVICE_ID,
    b.SWB_MATTER_ID,
    b.SWB_MATTER_NAME,
    b.SRC_MATTER_ID,
    b.AREA_CODE,
    b.PROJECT_NAME,
    b.PROMISE_DAY,
    b.PROMISE_DAY_UNIT,
    b.SWB_SN,
    b.SRC_SN,
    b.VERSION,
    b.PWD,
    b.DECLARE_TIME,
    b.RECEIVE_DEPT_NAME,
    b.RECEIVE_DEPT_CODE,
    b.ACCEPT_ADDRESS,
    b.SUB_WAY,
    b.QUEUING_NO,
    b.CENTRAL_APPROVAL_ITEMID,
    b.REL_ITEM_FLAG,
    b.REL_DEPT_CODE,
    b.REL_CENTRAL_ITEM_CODE,
    b.CLASS_UNID,
    b.CLASS_NAME,
    c.CLOUD_FORM_ID,
    c.INTRANET_URL,
    c.OUTERNET_URL,
    d.EXPRESS_ID,
    d.RECIPIENTS,
    d.R_CITY,
    d.R_ADDRESS,
    d.R_AREA_CODE,
    d.R_MOBILE,
    d.R_CONTACT_NUMBER,
    d.R_PAY_TYPE,
    e.IS_AGENT_SERVICE,
    e.AGENT_SERVICE_CHARGE,
    e.BACKFLOW,
    e.GZCNSP_FLAG,
    e.GZCNSP_FILE_UNID,
    e.GZCNSP_FILE_NAME,
    e.AGENT_SOURCE_AREA,
    e.CERTIFIED_IS_WRITE_OFF,
    f.OPERATOR_APPLY_NAME,
    f.OPERATOR_SEX,
    f.OPERATOR_BIRTHDAY,
    f.OPERATOR_CERTIFICATE_TYPE,
    f.OPERATOR_CERTIFICATE_NAME,
    f.OPERATOR_CERTIFICATE_NUMBER,
    f.OPERATOR_ADDRESS,
    f.OPERATOR_POSTCODE,
    f.OPERATOR_MOBILE_PHONE,
    f.OPERATOR_MAIL,
    f.OPERATOR_TEL,
    g.APPLYNAME,
    g.SEX,
    g.BIRTHDAY,
    g.CERTIFICATETYPE,
    g.CERTIFICATENAME,
    g.CERTIFICATENUMBER,
    g.ADDRESS,
    g.POSTCODE,
    g.MOBILEPHONE,
    g.MAIL,
    g.TEL,
    h.APPLY_TYPE,
    h.APPLY_OBJ_AREA_CODE,
    i.SMS_RECEIVER,
    i.SMS_ADDRESS,
    i.SMS_CONTENT,
		a.RESOURCEINFO_TYPE,
		a.OPERATION_LOGO,
    (SELECT COUNT(0) FROM HLWJ.FORM_INFO j WHERE j.BUSISYSINFO_UUID = a.UNID) AS FORM_INFO_DATA,
    (SELECT COUNT(0) FROM HLWJ.FORM_INFO_ITEM k,HLWJ.FORM_INFO j WHERE j.BUSISYSINFO_UUID = a.UNID AND k.DATA_ID = j.FORM_INFO_ID) AS INFO_ITEM_DATA
FROM
    HLWJ.CONVERT_DATA a
    LEFT JOIN HLWJ.WSSP_APASINFO b ON a.UNID = b.BUSISYSINFO_UUID
    LEFT JOIN HLWJ.WSSP_CLOUD_FORM c ON a.UNID = c.BUSISYSINFO_UUID
    LEFT JOIN HLWJ.WSSP_EXPRESS d ON d.BUSISYSINFO_UUID = a.UNID
    LEFT JOIN HLWJ.WSSP_EXTEND e ON e.BUSISYSINFO_UUID = a.UNID
    LEFT JOIN HLWJ.WSSP_OPERATOR f ON f.BUSISYSINFO_UUID = a.UNID
    LEFT JOIN HLWJ.WSSP_PERSON g ON g.DATA_ID = a.UNID
    LEFT JOIN HLWJ.WSSP_PROPOSER h ON h.BUSISYSINFO_UUID = a.UNID
    LEFT JOIN HLWJ.WSSP_SMS i ON i.BUSISYSINFO_UUID = a.UNID
    LEFT JOIN HLWJ.ROUTER l ON l.DATA_ID = a.UNID
WHERE
    a.WSSP_DATA_TYPE = '210';

-- ----------------------------
-- Sequence structure for SEQ_CFG_MONITOR_PROGRAM
-- ----------------------------
DROP SEQUENCE "HLWJ"."SEQ_CFG_MONITOR_PROGRAM";
CREATE SEQUENCE "HLWJ"."SEQ_CFG_MONITOR_PROGRAM" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 CACHE 10;

-- ----------------------------
-- Primary Key structure for table CONVERT_DATA
-- ----------------------------
ALTER TABLE "HLWJ"."CONVERT_DATA" ADD CONSTRAINT "SYS_C0013593" PRIMARY KEY ("UNID");

-- ----------------------------
-- Checks structure for table CONVERT_DATA
-- ----------------------------
ALTER TABLE "HLWJ"."CONVERT_DATA" ADD CONSTRAINT "SYS_C0013596" CHECK ("UNID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table DOCUMENT
-- ----------------------------
ALTER TABLE "HLWJ"."DOCUMENT" ADD CONSTRAINT "SYS_C0013505" PRIMARY KEY ("DOCUMENT_ID");

-- ----------------------------
-- Checks structure for table DOCUMENT
-- ----------------------------
ALTER TABLE "HLWJ"."DOCUMENT" ADD CONSTRAINT "SYS_C0013544" CHECK ("DOCUMENT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table DOCUMENT
-- ----------------------------
CREATE TRIGGER "HLWJ"."DOCUMENT_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."DOCUMENT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.DOCUMENT_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table FINISH_APASINFO
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_APASINFO" ADD CONSTRAINT "SYS_C0013507" PRIMARY KEY ("FINISH_APASINFO_ID");

-- ----------------------------
-- Checks structure for table FINISH_APASINFO
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_APASINFO" ADD CONSTRAINT "SYS_C0013546" CHECK ("FINISH_APASINFO_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table FINISH_APASINFO
-- ----------------------------
CREATE TRIGGER "HLWJ"."FINISH_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."FINISH_APASINFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.FINISH_APASINFO_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table FINISH_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_ATTR" ADD CONSTRAINT "SYS_C0013509" PRIMARY KEY ("ATTR_ID");

-- ----------------------------
-- Checks structure for table FINISH_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_ATTR" ADD CONSTRAINT "SYS_C0013548" CHECK ("ATTR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table FINISH_ATTR
-- ----------------------------
CREATE TRIGGER "HLWJ"."FINISH_ATTR_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."FINISH_ATTR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.ATTR_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table FINISH_LICENSE
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_LICENSE" ADD CONSTRAINT "SYS_C0013511" PRIMARY KEY ("FINISH_LICENSE_ID");

-- ----------------------------
-- Checks structure for table FINISH_LICENSE
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_LICENSE" ADD CONSTRAINT "SYS_C0013550" CHECK ("FINISH_LICENSE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table FINISH_RESULT_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_RESULT_ATTR" ADD CONSTRAINT "SYS_C0013594" CHECK ("FINISH_RESULT_ATTR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FINISH_SMS
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_SMS" ADD CONSTRAINT "SYS_C0013515" PRIMARY KEY ("FINISH_SMS_ID");

-- ----------------------------
-- Checks structure for table FINISH_SMS
-- ----------------------------
ALTER TABLE "HLWJ"."FINISH_SMS" ADD CONSTRAINT "SYS_C0013554" CHECK ("FINISH_SMS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table FINISH_SMS
-- ----------------------------
CREATE TRIGGER "HLWJ"."FINISH_SMS_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."FINISH_SMS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.FINISH_SMS_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table FORM_INFO
-- ----------------------------
ALTER TABLE "HLWJ"."FORM_INFO" ADD CONSTRAINT "SYS_C0013517" PRIMARY KEY ("FORM_INFO_ID");

-- ----------------------------
-- Checks structure for table FORM_INFO
-- ----------------------------
ALTER TABLE "HLWJ"."FORM_INFO" ADD CONSTRAINT "SYS_C0013556" CHECK ("FORM_INFO_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table FORM_INFO_ITEM
-- ----------------------------
ALTER TABLE "HLWJ"."FORM_INFO_ITEM" ADD CONSTRAINT "SYS_C0013519" PRIMARY KEY ("ITEM_ID");

-- ----------------------------
-- Checks structure for table FORM_INFO_ITEM
-- ----------------------------
ALTER TABLE "HLWJ"."FORM_INFO_ITEM" ADD CONSTRAINT "SYS_C0013558" CHECK ("ITEM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table FORM_INFO_ITEM
-- ----------------------------
CREATE TRIGGER "HLWJ"."FORM_INFO_ITEM_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."FORM_INFO_ITEM" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table NEXT_APAS_INFO
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_APAS_INFO" ADD CONSTRAINT "SYS_C0013521" PRIMARY KEY ("NEXT_APAS_INFO_ID");

-- ----------------------------
-- Checks structure for table NEXT_APAS_INFO
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_APAS_INFO" ADD CONSTRAINT "SYS_C0013568" CHECK ("NEXT_APAS_INFO_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table NEXT_APAS_INFO
-- ----------------------------
CREATE TRIGGER "HLWJ"."NEXT_APAS_INFO_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."NEXT_APAS_INFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.NEXT_APAS_INFO_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table NEXT_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_ATTR" ADD CONSTRAINT "SYS_C0013589" PRIMARY KEY ("NEXT_ATTR_ID");

-- ----------------------------
-- Checks structure for table NEXT_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_ATTR" ADD CONSTRAINT "SYS_C0013588" CHECK ("NEXT_ATTR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table NEXT_ATTR
-- ----------------------------
CREATE TRIGGER "HLWJ"."NEXT_ATTR_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."NEXT_ATTR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.NEXT_ATTR_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table NEXT_NODE
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_NODE" ADD CONSTRAINT "SYS_C0013523" PRIMARY KEY ("NEXT_NODE_ID");

-- ----------------------------
-- Checks structure for table NEXT_NODE
-- ----------------------------
ALTER TABLE "HLWJ"."NEXT_NODE" ADD CONSTRAINT "SYS_C0013570" CHECK ("NEXT_NODE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table NEXT_NODE
-- ----------------------------
CREATE TRIGGER "HLWJ"."NEXT_NODE_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."NEXT_NODE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.NEXT_NODE_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table ROUTER
-- ----------------------------
ALTER TABLE "HLWJ"."ROUTER" ADD CONSTRAINT "SYS_C0013525" PRIMARY KEY ("ROUTER_ID");

-- ----------------------------
-- Checks structure for table ROUTER
-- ----------------------------
ALTER TABLE "HLWJ"."ROUTER" ADD CONSTRAINT "SYS_C0013572" CHECK ("ROUTER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table ROUTER
-- ----------------------------
CREATE TRIGGER "HLWJ"."ROUTER_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."ROUTER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.ROUTER_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table SPECIAL_END
-- ----------------------------
ALTER TABLE "HLWJ"."SPECIAL_END" ADD CONSTRAINT "SYS_C0013527" PRIMARY KEY ("SPECIAL_END_ID");

-- ----------------------------
-- Triggers structure for table SPECIAL_END
-- ----------------------------
CREATE TRIGGER "HLWJ"."SPECIAL_END_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."SPECIAL_END" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.SPECIAL_END_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table SPECIAL_START
-- ----------------------------
ALTER TABLE "HLWJ"."SPECIAL_START" ADD CONSTRAINT "SYS_C0013529" PRIMARY KEY ("SPECIAL_START_ID");

-- ----------------------------
-- Checks structure for table SPECIAL_START
-- ----------------------------
ALTER TABLE "HLWJ"."SPECIAL_START" ADD CONSTRAINT "SYS_C0013575" CHECK ("SPECIAL_START_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table SPECIAL_START
-- ----------------------------
CREATE TRIGGER "HLWJ"."SPECIAL_START_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."SPECIAL_START" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.SPECIAL_START_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table SUPP_MAT
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT" ADD CONSTRAINT "SYS_C0013531" PRIMARY KEY ("SUPP_MAT_ID");

-- ----------------------------
-- Checks structure for table SUPP_MAT
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT" ADD CONSTRAINT "SYS_C0013577" CHECK ("SUPP_MAT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table SUPP_MAT
-- ----------------------------
CREATE TRIGGER "HLWJ"."SUPP_MAT_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."SUPP_MAT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.SUPP_MAT_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table SUPP_MAT_START
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT_START" ADD CONSTRAINT "SYS_C0013533" PRIMARY KEY ("SUPP_MAT_START_ID");

-- ----------------------------
-- Checks structure for table SUPP_MAT_START
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT_START" ADD CONSTRAINT "SYS_C0013579" CHECK ("SUPP_MAT_START_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table SUPP_MAT_START
-- ----------------------------
CREATE TRIGGER "HLWJ"."SUPP_MAT_START_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."SUPP_MAT_START" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.SUPP_MAT_START_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table SUPP_MAT_START_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT_START_ATTR" ADD CONSTRAINT "SYS_C0013583" PRIMARY KEY ("SUPP_MAT_START_ATTR_ID");

-- ----------------------------
-- Checks structure for table SUPP_MAT_START_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."SUPP_MAT_START_ATTR" ADD CONSTRAINT "SYS_C0013581" CHECK ("SUPP_MAT_START_ATTR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table WSSP_APASINFO
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_APASINFO" ADD CONSTRAINT "SYS_C0013537" PRIMARY KEY ("APASINFO_ID");

-- ----------------------------
-- Triggers structure for table WSSP_APASINFO
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_APASINFO_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_APASINFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.APASINFO_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_ATTR" ADD CONSTRAINT "SYS_C0013503" PRIMARY KEY ("ATTR_ID");

-- ----------------------------
-- Checks structure for table WSSP_ATTR
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_ATTR" ADD CONSTRAINT "SYS_C0013542" CHECK ("ATTR_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table WSSP_ATTR
-- ----------------------------
CREATE TRIGGER "HLWJ"."ATTR_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_ATTR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.ATTR_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_CLOUD_FORM
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_CLOUD_FORM" ADD CONSTRAINT "SYS_C0013539" PRIMARY KEY ("CLOUD_FORM_ID");

-- ----------------------------
-- Checks structure for table WSSP_CLOUD_FORM
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_CLOUD_FORM" ADD CONSTRAINT "SYS_C0013585" CHECK ("CLOUD_FORM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table WSSP_CLOUD_FORM
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_CLOUD_FORM_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_CLOUD_FORM" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.CLOUD_FORM_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_EXPRESS
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_EXPRESS" ADD CONSTRAINT "EXPRESS_PK" PRIMARY KEY ("EXPRESS_ID");

-- ----------------------------
-- Triggers structure for table WSSP_EXPRESS
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_EXPRESS_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_EXPRESS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.EXPRESS_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_EXTEND
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_EXTEND" ADD CONSTRAINT "EXTEND_PK" PRIMARY KEY ("EXTEND_ID");

-- ----------------------------
-- Triggers structure for table WSSP_EXTEND
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_EXTEND_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_EXTEND" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.EXTEND_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_OPERATOR
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_OPERATOR" ADD CONSTRAINT "OPERATOR_PK" PRIMARY KEY ("OPERATOR_ID");

-- ----------------------------
-- Triggers structure for table WSSP_OPERATOR
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_OPERATOR_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_OPERATOR" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.OPERATOR_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_PERSON
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_PERSON" ADD CONSTRAINT "SYS_C0013492" PRIMARY KEY ("WSSP_PERSON_ID");

-- ----------------------------
-- Triggers structure for table WSSP_PERSON
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_PERSON_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_PERSON" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.WSSP_PERSON_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_PROPOSER
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_PROPOSER" ADD CONSTRAINT "PROPOSER_PK" PRIMARY KEY ("PROPOSER_ID");

-- ----------------------------
-- Checks structure for table WSSP_PROPOSER
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_PROPOSER" ADD CONSTRAINT "SYS_C0013396" CHECK ("PROPOSER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table WSSP_PROPOSER
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_PROPOSER_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_PROPOSER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.PROPOSER_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_SMS
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_SMS" ADD CONSTRAINT "SMS_PK" PRIMARY KEY ("SMS_ID");

-- ----------------------------
-- Triggers structure for table WSSP_SMS
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_SMS_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_SMS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.SMS_ID FROM DUAL;
END;
/

-- ----------------------------
-- Primary Key structure for table WSSP_UNIT
-- ----------------------------
ALTER TABLE "HLWJ"."WSSP_UNIT" ADD CONSTRAINT "UNIT_PK" PRIMARY KEY ("UNIT_ID");

-- ----------------------------
-- Triggers structure for table WSSP_UNIT
-- ----------------------------
CREATE TRIGGER "HLWJ"."WSSP_UNIT_INSERT_NEW_ID" BEFORE INSERT ON "HLWJ"."WSSP_UNIT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
BEGIN
    SELECT SEQ_CFG_MONITOR_PROGRAM.NEXTVAL INTO :NEW.UNIT_ID FROM DUAL;
END;
/
